# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operator_tip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_tip(object):
    def setupUi(self, show_tip):
        show_tip.setObjectName("show_tip")
        show_tip.resize(800, 500)
        show_tip.setMinimumSize(QtCore.QSize(800, 500))
        show_tip.setMaximumSize(QtCore.QSize(1920, 1080))
        show_tip.setSizeIncrement(QtCore.QSize(0, 0))
        show_tip.setStyleSheet("")
        self.label = QtWidgets.QLabel(show_tip)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 500))
        self.label.setMinimumSize(QtCore.QSize(800, 500))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(show_tip)
        QtCore.QMetaObject.connectSlotsByName(show_tip)

    def retranslateUi(self, show_tip):
        _translate = QtCore.QCoreApplication.translate
        show_tip.setWindowTitle(_translate("show_tip", "Form"))
import card
