# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_show_record(object):
    def setupUi(self, show_record):
        show_record.setObjectName("show_record")
        show_record.resize(400, 400)
        show_record.setMinimumSize(QtCore.QSize(400, 400))
        show_record.setStyleSheet("background-color: #ffffff;\n"
"    border: 2px solid #ff9292;\n"
"    border-radius: 6px;")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(show_record)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(show_record)
        self.label.setMinimumSize(QtCore.QSize(110, 20))
        font = QtGui.QFont()
        font.setFamily("字魂蜜桃猫体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"border: none;\n"
"    color: #ff9292;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(show_record)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: #ff9292;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"color: #ffffff;\n"
"border-color: #ff9292;\n"
"background-color: #ff9292;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(show_record)
        self.textEdit.setMinimumSize(QtCore.QSize(380, 350))
        self.textEdit.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: #ff9292;\n"
"border: 2px solid #ff9292;\n"
"border-radius: 5px;")
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(show_record)
        QtCore.QMetaObject.connectSlotsByName(show_record)

    def retranslateUi(self, show_record):
        _translate = QtCore.QCoreApplication.translate
        show_record.setWindowTitle(_translate("show_record", "record"))
        self.label.setText(_translate("show_record", "记录以及信息"))
        self.pushButton.setText(_translate("show_record", "×"))
